-- Create vehicles table
CREATE TABLE IF NOT EXISTS `vehicles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_number` varchar(50) DEFAULT NULL,
  `customer_name` varchar(100) NOT NULL,
  `customer_number1` varchar(20) NOT NULL,
  `customer_number2` varchar(20) DEFAULT NULL,
  `customer_email` varchar(100) DEFAULT NULL,
  `current_address` text DEFAULT NULL,
  `permanent_address` text DEFAULT NULL,
  `postal_pin` varchar(20) DEFAULT NULL,
  `nomini_name` varchar(100) DEFAULT NULL,
  `nomini_dob` date DEFAULT NULL,
  `company_name` varchar(100) DEFAULT NULL,
  `gst_number` varchar(50) DEFAULT NULL,
  `vehicle_number` varchar(20) NOT NULL,
  `make_model` varchar(100) DEFAULT NULL,
  `reg_date` date DEFAULT NULL,
  `policy_no` varchar(50) DEFAULT NULL,
  `policy_company` varchar(100) DEFAULT NULL,
  `policy_start_date` date DEFAULT NULL,
  `policy_end_date` date DEFAULT NULL,
  `gross_amount` decimal(10,2) DEFAULT 0.00,
  `net_amount` decimal(10,2) DEFAULT 0.00,
  `commission` decimal(10,2) DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `policy_no` (`policy_no`),
  KEY `vehicle_number` (`vehicle_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
